# Generated by Django 2.0.6 on 2018-09-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='istype',
            field=models.SmallIntegerField(default=0),
        ),
    ]
